# Generated by Django 3.2 on 2021-04-24 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('article_image', models.ImageField(upload_to='')),
                ('intro', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(100)])),
                ('article_content', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)])),
            ],
        ),
    ]
