# Generated by Django 3.2 on 2021-04-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
